# -*- coding: utf-8 -*-
"""
Created on Wed Sep 11 05:26:10 2019

@author: dcamp
"""

from sklearn import datasets
import matplotlib.pyplot as plt 
from sklearn.manifold import TSNE

# Exploratory data analysis (EDA, for short)
plt.style.use('ggplot')
iris = datasets.load_iris()
print(type(iris))
print(iris.keys())
print(type(iris.data), type(iris.target))
print(iris.data.shape)
print(iris.target_names)

X = iris.data
y = iris.target 

#   Normally the learning rate should be between 50 and 100
model = TSNE(learning_rate=100)
transformed = model.fit_transform(X)

# T-SNE transforms any number of variables into a two dimensional set of features for visualization purposes
X_0 = transformed[:,0]
X_1 = transformed[:,1]

# The 2-axes generated by T-SNE do not have any explicit meaning. Each time features are transformed, the values of the axes vary but the distance between samples will reamin the same
plt.scatter(X_0, X_1, c=y)
plt.show()
